spring:
  messages:
    basename: i18n/messages   # 资源文件前缀（不带 .properties）
    encoding: UTF-8
    fallback-to-system-locale: false    # 禁用系统语言回退
    default-locale: zh_CN               # 默认语言
    cache-duration: 3600s               # 缓存时间（生产建议开启）
  application:
    name: youlai-boot
  profiles:
    active: dev
  config:
    import: classpath:codegen.yml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# 在 banner.txt 中显示项目版本，使用 @project.version@ 从 pom.xml 获取
project:
  version: @project.version@
